services:
  backend:
    build:
      context: ./backdjango
    container_name: tp-django-backend
    volumes:
      - ./backdjango:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontangular
    container_name: tp-angular-frontend
    volumes:
      - ./frontangular/geoapiview:/app
    working_dir: /app
    ports:
      - "4200:4200"
    command: npm run start

  redis:
    image: redis:7
    container_name: tp-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
